// Elden Ring Nightreign - Static Data
// Sources: fextralife.com/wiki and bandainamcoent.eu

const CHARACTERS = {
  wylder: {
    id: 'wylder',
    name: 'Wylder',
    description: 'A balanced all-rounder. Proficient with melee weapons, particularly greatswords. Suitable for newcomers.',
    image: null,
    scaling: { str: 'A', dex: 'B', int: 'C', fai: 'C', arc: 'C' },
    lvl1: { hp: 240, fp: 65, stamina: 54, vig: 8, mnd: 4, end: 5, str: 6, dex: 5, int: 4, fai: 4, arc: 10 },
    lvl15: { hp: 1120, fp: 140, stamina: 102, vig: 52, mnd: 19, end: 27, str: 50, dex: 40, int: 15, fai: 15, arc: 10 },
    passive: { name: 'Sixth Sense', desc: 'Cheat death a single time. Effect replenishes at Sites of Grace or upon respawning.' },
    skill:   { name: 'Claw Shot', desc: 'Launches a grappling mechanism that pulls smaller enemies toward the user or draws the user toward larger foes.', cooldown: '8s' },
    ultimate:{ name: 'Onslaught Stake', desc: 'Powerful single attack that launches an iron stake with a great explosion. Can be charged for increased potency.' },
    startingEquipment: ["Wylder's Greatsword", "Wylder's Small Shield", "Wylder's Urn"],
  },
  guardian: {
    id: 'guardian',
    name: 'Guardian',
    description: 'A defensive powerhouse with a massive shield. Excels at protecting allies and absorbing damage.',
    image: null,
    scaling: { str: 'B', dex: 'C', int: 'D', fai: 'C', arc: 'C' },
    lvl1: { hp: 280, fp: 55, stamina: 60, vig: 10, mnd: 2, end: 6, str: 4, dex: 3, int: 2, fai: 3, arc: 10 },
    lvl15: { hp: 1280, fp: 115, stamina: 124, vig: 60, mnd: 14, end: 38, str: 39, dex: 29, int: 10, fai: 21, arc: 10 },
    passive: { name: 'Steel Guard', desc: 'Plant feet and brace with shield for more powerful guard. Multiplies shield Guard Boost by 5x, reducing stamina damage from blocking.' },
    skill:   { name: 'Whirlwind', desc: 'Beat wing to whip up a wind-churning cyclone. A 360-degree attack that can be charged for expanded area of effect.', cooldown: null },
    ultimate:{ name: 'Wings of Salvation', desc: 'Leap up and dive back down to raise protective area. Instantly resurrects nearby allies and grants damage immunity within the aura.' },
    startingEquipment: ["Guardian's Greatshield", "Guardian's Spear"],
  },
  ironeye: {
    id: 'ironeye',
    name: 'Ironeye',
    description: 'A precision ranged fighter with keen observation skills. Excels with bows and exploiting enemy weak points.',
    image: null,
    scaling: { str: 'C', dex: 'A', int: 'D', fai: 'D', arc: 'B' },
    lvl1: { hp: 200, fp: 55, stamina: 56, vig: 6, mnd: 2, end: 4, str: 4, dex: 8, int: 2, fai: 2, arc: 13 },
    lvl15: { hp: 820, fp: 115, stamina: 104, vig: 37, mnd: 14, end: 28, str: 19, dex: 57, int: 7, fai: 13, arc: 13 },
    passive: { name: 'Eagle Eye', desc: 'A keenly observant eye discovers more items to obtain from foes.' },
    skill:   { name: 'Marking', desc: 'Delivers a dagger strike that creates a temporary weak point on enemies, dealing additional damage. Teammates can exploit vulnerabilities.', cooldown: null },
    ultimate:{ name: 'Single Shot', desc: "Fires a powerful arrow that surpasses sound and ignores any defense, creating a shockwave that damages enemies in a large area." },
    startingEquipment: ["Ironeye's Longbow", "Ironeye's Dagger"],
  },
  duchess: {
    id: 'duchess',
    name: 'Duchess',
    description: 'A graceful hybrid fighter with exceptional dodge mechanics and the ability to replay past attacks.',
    image: null,
    scaling: { str: 'D', dex: 'B', int: 'A', fai: 'B', arc: 'C' },
    lvl1: { hp: 220, fp: 75, stamina: 54, vig: 7, mnd: 6, end: 3, str: 2, dex: 4, int: 4, fai: 3, arc: 11 },
    lvl15: { hp: 860, fp: 180, stamina: 84, vig: 39, mnd: 27, end: 18, str: 11, dex: 45, int: 42, fai: 27, arc: 11 },
    passive: { name: 'Magnificent Poise', desc: 'Attack and dodge optimally — allows a second dodge input when dodging repeatedly.' },
    skill:   { name: 'Restage', desc: 'Stage reprisal of recent occurrences to damage nearby foes — replicates 50% of damage inflicted in the last 3 seconds.', cooldown: null },
    ultimate:{ name: 'Finale', desc: 'Obscure self and surrounding allies to hide from foes for approximately 10 seconds.' },
    startingEquipment: ["Duchess's Rapier", "Duchess's Robe"],
  },
  raider: {
    id: 'raider',
    name: 'Raider',
    description: 'An unstoppable brawler with massive Strength scaling. Cannot be knocked down while using key abilities.',
    image: null,
    scaling: { str: 'S', dex: 'C', int: 'D', fai: 'D', arc: 'C' },
    lvl1: { hp: 260, fp: 55, stamina: 60, vig: 9, mnd: 2, end: 6, str: 9, dex: 4, int: 1, fai: 2, arc: 10 },
    lvl15: { hp: 1200, fp: 95, stamina: 122, vig: 56, mnd: 10, end: 37, str: 68, dex: 19, int: 3, fai: 12, arc: 10 },
    passive: { name: "Fighter's Resolve", desc: 'Taking damage boosts Retaliate potency. Cannot be knocked down while using Retaliate.' },
    skill:   { name: 'Retaliate', desc: 'Assume attack stance and pummel vigorously. Reduces damage taken when activated and performs powerful punches.', cooldown: null },
    ultimate:{ name: 'Totem Stela', desc: "Drive gravekeeper's wedge into earth to summon a giant tombstone. Provides protective auras and strength buffs to allies for 20 seconds." },
    startingEquipment: ["Raider's Flail", "Raider's Armor"],
  },
  recluse: {
    id: 'recluse',
    name: 'Recluse',
    description: 'A powerful dual-school spellcaster who collects elemental residues to fuel devastating magic cocktails.',
    image: null,
    scaling: { str: 'D', dex: 'C', int: 'S', fai: 'S', arc: 'C' },
    lvl1: { hp: 200, fp: 80, stamina: 54, vig: 6, mnd: 7, end: 3, str: 1, dex: 2, int: 5, fai: 5, arc: 10 },
    lvl15: { hp: 740, fp: 195, stamina: 94, vig: 33, mnd: 30, end: 23, str: 12, dex: 19, int: 51, fai: 51, arc: 10 },
    passive: { name: 'Residue Harvest', desc: 'Discover affinity residues that can be collected to replenish FP.' },
    skill:   { name: 'Affinity Cocktail', desc: 'Collect elemental residues to fire an affinity-exploiting magic cocktail with effects based on element combinations.', cooldown: null },
    ultimate:{ name: 'Soulblood Song', desc: 'Marks nearby enemies — when yourself or allies strike any of these enemies, they will regain HP and FP.' },
    startingEquipment: ["Recluse's Staff", "Recluse's Seal"],
  },
  executor: {
    id: 'executor',
    name: 'Executor',
    description: 'A cursed swordsman who excels at status ailment recovery and Sekiro-style deflection combat.',
    image: null,
    scaling: { str: 'C', dex: 'S', int: 'D', fai: 'D', arc: 'S' },
    lvl1: { hp: 220, fp: 55, stamina: 54, vig: 7, mnd: 2, end: 3, str: 5, dex: 8, int: 2, fai: 2, arc: 28 },
    lvl15: { hp: 1000, fp: 100, stamina: 102, vig: 46, mnd: 11, end: 27, str: 25, dex: 63, int: 8, fai: 6, arc: 28 },
    passive: { name: 'Ailment Recovery', desc: 'Receive boost after recovering from status ailments — provides attack power and stamina recovery for ~20 seconds.' },
    skill:   { name: 'Cursed Deflect', desc: 'Draw a cursed sword enabling deflection mechanics with a generous deflect window and negligible stamina consumption.', cooldown: null },
    ultimate:{ name: 'Beast Transformation', desc: 'Transform into a primordial beast form granting access to unique attacks and crowd control options for ~15 seconds.' },
    startingEquipment: ["Executor's Katana", "Executor's Mask"],
  },
  revenant: {
    id: 'revenant',
    name: 'Revenant',
    description: 'A necromancer who raises fallen enemies as allies and can make the entire party temporarily immortal.',
    image: null,
    scaling: { str: 'C', dex: 'C', int: 'B', fai: 'S', arc: 'B' },
    lvl1: { hp: 200, fp: 80, stamina: 54, vig: 6, mnd: 7, end: 3, str: 2, dex: 2, int: 4, fai: 5, arc: 12 },
    lvl15: { hp: 780, fp: 200, stamina: 90, vig: 35, mnd: 31, end: 21, str: 21, dex: 21, int: 30, fai: 51, arc: 12 },
    passive: { name: 'Necromancy', desc: 'Raise enemy ghosts to fight as allies — reanimates defeated foes as temporary phantom allies.' },
    skill:   { name: 'Summon Spirit', desc: 'Play lyre to summon fallen family to rally in battle — deploys one of three summons: Helen, Frederick, or Sebastian.', cooldown: null },
    ultimate:{ name: 'Immortal March', desc: 'Release vengeful ire to make self and nearby allies immortal for 15 seconds, preventing lethal damage and reviving downed teammates.' },
    startingEquipment: ["Revenant's Seal", "Revenant's Lyre"],
  },
  scholar: {
    id: 'scholar',
    name: 'Scholar',
    description: '(DLC - Forsaken Hollows) A specialist in Arcane who leverages unique knowledge-based abilities.',
    image: null,
    isDLC: true,
    scaling: { str: 'D', dex: 'C', int: 'C', fai: 'C', arc: 'S' },
    lvl1: { hp: 220, fp: 65, stamina: 54, vig: 7, mnd: 5, end: 3, str: 2, dex: 3, int: 4, fai: 4, arc: 15 },
    lvl15: { hp: 900, fp: 155, stamina: 90, vig: 42, mnd: 22, end: 22, str: 12, dex: 18, int: 20, fai: 20, arc: 45 },
    passive: { name: 'Scholar Passive', desc: 'Details not yet confirmed — DLC character.' },
    skill:   { name: 'Scholar Skill', desc: 'Details not yet confirmed — DLC character.', cooldown: null },
    ultimate:{ name: 'Scholar Ultimate', desc: 'Details not yet confirmed — DLC character.' },
    startingEquipment: ["Scholar's Tome"],
  },
  undertaker: {
    id: 'undertaker',
    name: 'Undertaker',
    description: '(DLC - Forsaken Hollows) A Strength/Faith hybrid focused on powerful weapon arts.',
    image: null,
    isDLC: true,
    scaling: { str: 'A', dex: 'D', int: 'D', fai: 'A', arc: 'C' },
    lvl1: { hp: 220, fp: 65, stamina: 54, vig: 7, mnd: 5, end: 3, str: 7, dex: 2, int: 2, fai: 7, arc: 10 },
    lvl15: { hp: 980, fp: 140, stamina: 100, vig: 45, mnd: 19, end: 24, str: 50, dex: 12, int: 8, fai: 50, arc: 10 },
    passive: { name: 'Undertaker Passive', desc: 'Details not yet confirmed — DLC character.' },
    skill:   { name: 'Undertaker Skill', desc: 'Details not yet confirmed — DLC character.', cooldown: null },
    ultimate:{ name: 'Undertaker Ultimate', desc: 'Details not yet confirmed — DLC character.' },
    startingEquipment: ["Undertaker's Sword"],
  },
};

// Talisman data (up to 2 equipped)
const TALISMANS = [
  { id: 'ancestral_horn', name: "Ancestral Spirit's Horn", effects: [{ stat: 'fpOnKill', type: 'percent', value: 5, label: 'FP on kill +5%' }] },
  { id: 'arrows_reach', name: "Arrow's Reach Talisman", effects: [{ stat: 'projectileRange', type: 'percent', value: 100, label: 'Projectile range +100%' }] },
  { id: 'arrows_sting', name: "Arrow's Sting Talisman", effects: [{ stat: 'rangedAtk', type: 'percent', value: 14, label: 'Ranged attack +14%' }] },
  { id: 'assassins_cerulean', name: "Assassin's Cerulean Dagger", effects: [{ stat: 'fp', type: 'onCritical', value: 10, label: 'Critical hit FP restore +10%' }] },
  { id: 'assassins_crimson', name: "Assassin's Crimson Dagger", effects: [{ stat: 'hp', type: 'onCritical', value: 18, label: 'Critical hit HP restore +18%' }] },
  { id: 'axe_talisman', name: 'Axe Talisman', effects: [{ stat: 'chargeAtk', type: 'percent', value: 12, label: 'Charged attack +12%' }] },
  { id: 'blessed_dew', name: 'Blessed Dew Talisman', effects: [{ stat: 'hpRegen', type: 'flat', value: 2, label: 'HP regen +2/s' }] },
  { id: 'blue_feather', name: 'Blue-Feathered Branchsword', effects: [{ stat: 'damageNeg', type: 'lowHp', value: 50, label: 'Damage negation at low HP +50%' }] },
  { id: 'boltdrake', name: 'Boltdrake Talisman', effects: [{ stat: 'lightningNeg', type: 'percent', value: 20, label: 'Lightning negation +20%' }] },
  { id: 'bull_goat', name: "Bull-Goat's Talisman", effects: [{ stat: 'poise', type: 'percent', value: 25, label: 'Poise +25%' }] },
  { id: 'carian_crest', name: 'Carian Filigreed Crest', effects: [{ stat: 'skillFpCost', type: 'percent', value: -25, label: 'Skill FP cost -25%' }] },
  { id: 'cerulean_amber', name: 'Cerulean Amber Medallion', effects: [{ stat: 'fp', type: 'percent', value: 12, label: 'Max FP +12%' }] },
  { id: 'claw_talisman', name: 'Claw Talisman', effects: [{ stat: 'jumpAtk', type: 'percent', value: 12, label: 'Jump attack +12%' }] },
  { id: 'crimson_amber', name: 'Crimson Amber Medallion', effects: [{ stat: 'hp', type: 'percent', value: 12, label: 'Max HP +12%' }] },
  { id: 'crimson_seed', name: 'Crimson Seed Talisman', effects: [{ stat: 'flaskHp', type: 'percent', value: 20, label: 'Flask HP restoration +20%' }] },
  { id: 'crucible_feather', name: 'Crucible Feather Talisman', effects: [{ stat: 'dodge', type: 'improve', value: 1, label: 'Improved dodging' }, { stat: 'damageNeg', type: 'percent', value: -10, label: 'Damage negation -10%' }] },
  { id: 'dagger_talisman', name: 'Dagger Talisman', effects: [{ stat: 'criticalAtk', type: 'percent', value: 24, label: 'Critical hits +24%' }] },
  { id: 'dragoncrest_shield', name: 'Dragoncrest Shield Talisman', effects: [{ stat: 'physNeg', type: 'percent', value: 15, label: 'Physical negation +15%' }] },
  { id: 'erdtrees_favor', name: "Erdtree's Favor", effects: [{ stat: 'hp', type: 'percent', value: 7, label: 'Max HP +7%' }, { stat: 'stamina', type: 'percent', value: 7, label: 'Max Stamina +7%' }] },
  { id: 'faithful_canvas', name: "Faithful's Canvas Talisman", effects: [{ stat: 'incantations', type: 'percent', value: 11, label: 'Incantation power +11%' }] },
  { id: 'fire_scorpion', name: 'Fire Scorpion Charm', effects: [{ stat: 'fireAtk', type: 'percent', value: 15, label: 'Fire attack +15%' }, { stat: 'physNeg', type: 'percent', value: -3, label: 'Physical negation -3%' }] },
  { id: 'flamedrake', name: 'Flamedrake Talisman', effects: [{ stat: 'fireNeg', type: 'percent', value: 20, label: 'Fire negation +20%' }] },
  { id: 'godfrey_icon', name: 'Godfrey Icon', effects: [{ stat: 'chargedSpells', type: 'percent', value: 18, label: 'Charged spells & skills +18%' }] },
  { id: 'godskin_cloth', name: 'Godskin Swaddling Cloth', effects: [{ stat: 'hp', type: 'onSuccessive', value: 6, label: 'HP restore on successive attacks +6%' }] },
  { id: 'gold_scarab', name: 'Gold Scarab', effects: [{ stat: 'runes', type: 'percent', value: 15, label: 'Rune gain +15%' }] },
  { id: 'graven_school', name: 'Graven-School Talisman', effects: [{ stat: 'sorceries', type: 'percent', value: 11, label: 'Sorcery power +11%' }] },
  { id: 'greatshield_talisman', name: 'Greatshield Talisman', effects: [{ stat: 'guardAbility', type: 'percent', value: 20, label: 'Guard ability +20%' }] },
  { id: 'green_turtle', name: 'Green Turtle Talisman', effects: [{ stat: 'staminaRegen', type: 'flat', value: 8, label: 'Stamina regen +8/s' }] },
  { id: 'haligdrake', name: 'Haligdrake Talisman', effects: [{ stat: 'holyNeg', type: 'percent', value: 20, label: 'Holy negation +20%' }] },
  { id: 'kindred_rot', name: "Kindred of Rot's Exultation", effects: [{ stat: 'atkPower', type: 'onStatusNearby', value: 20, label: 'Attack power +20% on poison/rot nearby' }] },
  { id: 'lightning_scorpion', name: 'Lightning Scorpion Charm', effects: [{ stat: 'lightningAtk', type: 'percent', value: 15, label: 'Lightning attack +15%' }, { stat: 'physNeg', type: 'percent', value: -3, label: 'Physical negation -3%' }] },
  { id: 'lord_of_blood', name: "Lord of Blood's Exultation", effects: [{ stat: 'atkPower', type: 'onBloodloss', value: 20, label: 'Attack power +20% on bloodloss' }] },
  { id: 'magic_scorpion', name: 'Magic Scorpion Charm', effects: [{ stat: 'magicAtk', type: 'percent', value: 15, label: 'Magic attack +15%' }, { stat: 'physNeg', type: 'percent', value: -3, label: 'Physical negation -3%' }] },
  { id: 'millicent', name: "Millicent's Prosthesis", effects: [{ stat: 'dex', type: 'percent', value: 5, label: 'Dex +5%' }] },
  { id: 'mottled_necklace', name: 'Mottled Necklace', effects: [{ stat: 'statusRes', type: 'flat', value: 40, label: 'All status resistances +40' }] },
  { id: 'old_lords', name: "Old Lord's Talisman", effects: [{ stat: 'spellDuration', type: 'percent', value: 30, label: 'Spell duration +30%' }] },
  { id: 'pearldrake', name: 'Pearldrake Talisman', effects: [{ stat: 'nonPhysNeg', type: 'percent', value: 10, label: 'Non-physical negation +10%' }] },
  { id: 'primal_glintstone', name: 'Primal Glintstone Blade', effects: [{ stat: 'spellFpCost', type: 'flat', value: -25, label: 'Spell FP cost -25' }, { stat: 'hp', type: 'percent', value: -15, label: 'Max HP -15%' }] },
  { id: 'radagon_icon', name: 'Radagon Icon', effects: [{ stat: 'spellSpeed', type: 'flat', value: 60, label: 'Spell cast speed +60' }] },
  { id: 'red_feather', name: 'Red-Feathered Branchsword', effects: [{ stat: 'atkPower', type: 'lowHp', value: 20, label: 'Attack power at low HP +20%' }] },
  { id: 'ritual_shield', name: 'Ritual Shield Talisman', effects: [{ stat: 'damageNeg', type: 'fullHp', value: 30, label: 'Damage negation at full HP +30%' }] },
  { id: 'ritual_sword', name: 'Ritual Sword Talisman', effects: [{ stat: 'atkPower', type: 'fullHp', value: 10, label: 'Attack power at full HP +10%' }] },
  { id: 'roar_medallion', name: 'Roar Medallion', effects: [{ stat: 'roarAtk', type: 'percent', value: 20, label: 'Roar/Breath attacks +20%' }] },
  { id: 'sacred_scorpion', name: 'Sacred Scorpion Charm', effects: [{ stat: 'holyAtk', type: 'percent', value: 15, label: 'Holy attack +15%' }, { stat: 'physNeg', type: 'percent', value: -3, label: 'Physical negation -3%' }] },
  { id: 'sacrificial_twig', name: 'Sacrificial Twig', effects: [{ stat: 'noRuneLoss', type: 'special', value: 1, label: 'No rune loss on death' }] },
  { id: 'silver_scarab', name: 'Silver Scarab', effects: [{ stat: 'itemDiscovery', type: 'flat', value: 40, label: 'Item discovery +40' }] },
  { id: 'spear_talisman', name: 'Spear Talisman', effects: [{ stat: 'thrustCounter', type: 'percent', value: 20, label: 'Thrusting counterattack +20%' }] },
  { id: 'spelldrake', name: 'Spelldrake Talisman', effects: [{ stat: 'magicNeg', type: 'percent', value: 20, label: 'Magic negation +20%' }] },
  { id: 'takers_cameo', name: "Taker's Cameo", effects: [{ stat: 'hp', type: 'onKill', value: 6, label: 'HP restore on kill +6%' }] },
  { id: 'twinblade_talisman', name: 'Twinblade Talisman', effects: [{ stat: 'chainFinisher', type: 'percent', value: 15, label: 'Chain attack finishers +15%' }] },
  { id: 'viridian_amber', name: 'Viridian Amber Medallion', effects: [{ stat: 'stamina', type: 'percent', value: 12, label: 'Max Stamina +12%' }] },
  { id: 'warrior_jar', name: 'Warrior Jar Shard', effects: [{ stat: 'skillAtk', type: 'percent', value: 15, label: 'Skill attack power +15%' }] },
  { id: 'winged_sword', name: 'Winged Sword Insignia', effects: [{ stat: 'atkPower', type: 'successive', value: 1, label: 'Attack power stacks on successive hits' }] },
  { id: 'curved_sword', name: 'Curved Sword Talisman', effects: [{ stat: 'guardCounter', type: 'percent', value: 20, label: 'Guard counters +20%' }] },
  { id: 'companion_jar', name: 'Companion Jar', effects: [{ stat: 'throwingPots', type: 'percent', value: 20, label: 'Throwing pots +20%' }] },
  { id: 'hammer_talisman', name: 'Hammer Talisman', effects: [{ stat: 'guardBreak', type: 'percent', value: 50, label: 'Guard breaking +50%' }] },
];

// Relic effect categories (procedurally generated in game, so we provide common presets)
const RELIC_EFFECTS = [
  { id: 'phys_dmg', label: 'Physical Damage +8.5%', stat: 'physAtk', type: 'multiplier', value: 1.085 },
  { id: 'phys_dmg_lg', label: 'Physical Damage +10%', stat: 'physAtk', type: 'multiplier', value: 1.1 },
  { id: 'magic_dmg', label: 'Magic Damage +8.5%', stat: 'magicAtk', type: 'multiplier', value: 1.085 },
  { id: 'magic_dmg_lg', label: 'Magic Damage +10%', stat: 'magicAtk', type: 'multiplier', value: 1.1 },
  { id: 'fire_dmg', label: 'Fire Damage +8.5%', stat: 'fireAtk', type: 'multiplier', value: 1.085 },
  { id: 'lightning_dmg', label: 'Lightning Damage +8.5%', stat: 'lightningAtk', type: 'multiplier', value: 1.085 },
  { id: 'holy_dmg', label: 'Holy Damage +8.5%', stat: 'holyAtk', type: 'multiplier', value: 1.085 },
  { id: 'max_hp', label: 'Max HP +10%', stat: 'hp', type: 'percent', value: 10 },
  { id: 'max_fp', label: 'Max FP +10%', stat: 'fp', type: 'percent', value: 10 },
  { id: 'max_stamina', label: 'Max Stamina +10%', stat: 'stamina', type: 'percent', value: 10 },
  { id: 'skill_cooldown', label: 'Skill Cooldown -15%', stat: 'cooldown', type: 'percent', value: -15 },
  { id: 'skill_atk', label: 'Skill Attack Power +10%', stat: 'skillAtk', type: 'percent', value: 10 },
  { id: 'ultimate_power', label: 'Ultimate Art Power +10%', stat: 'ultimateAtk', type: 'percent', value: 10 },
  { id: 'crit_rate', label: 'Critical Rate +5%', stat: 'critRate', type: 'percent', value: 5 },
  { id: 'item_discovery', label: 'Item Discovery +20', stat: 'itemDiscovery', type: 'flat', value: 20 },
  { id: 'rune_gain', label: 'Rune Gain +10%', stat: 'runes', type: 'percent', value: 10 },
  { id: 'phys_neg', label: 'Physical Negation +5%', stat: 'physNeg', type: 'percent', value: 5 },
  { id: 'all_dmg_neg', label: 'All Damage Negation +5%', stat: 'allNeg', type: 'percent', value: 5 },
  { id: 'poise', label: 'Poise +15%', stat: 'poise', type: 'percent', value: 15 },
  { id: 'stamina_regen', label: 'Stamina Regen +5/s', stat: 'staminaRegen', type: 'flat', value: 5 },
  { id: 'fp_regen', label: 'FP Regen +2/s', stat: 'fpRegen', type: 'flat', value: 2 },
  { id: 'hp_regen', label: 'HP Regen +3/s', stat: 'hpRegen', type: 'flat', value: 3 },
  { id: 'poison_res', label: 'Poison Resistance +50', stat: 'poisonRes', type: 'flat', value: 50 },
  { id: 'bleed_res', label: 'Blood Loss Resistance +50', stat: 'bleedRes', type: 'flat', value: 50 },
  { id: 'frost_res', label: 'Frost Resistance +50', stat: 'frostRes', type: 'flat', value: 50 },
];

// Relic vessel slots (4 slots: red, green, blue, yellow)
const VESSEL_SLOTS = ['red', 'green', 'blue', 'yellow'];

// Max relics per slot (Delicate=1, Polished=2, Grand=3 effects)
const RELIC_TIERS = [
  { id: 'delicate', name: 'Delicate', effects: 1 },
  { id: 'polished', name: 'Polished', effects: 2 },
  { id: 'grand', name: 'Grand', effects: 3 },
];
