// Elden Ring Nightreign - Static Data
// Sources: fextralife.com/wiki and bandainamcoent.eu

const CHARACTERS = {
  wylder: {
    id: 'wylder',
    name: 'Wylder',
    description: 'A balanced all-rounder. Proficient with melee weapons, particularly greatswords. Suitable for newcomers.',
    image: null,
    scaling: { str: 'A', dex: 'B', int: 'C', fai: 'C', arc: 'C' },
    lvl1: { hp: 240, fp: 65, stamina: 54, vig: 8, mnd: 4, end: 5, str: 6, dex: 5, int: 4, fai: 4, arc: 10 },
    lvl15: { hp: 1120, fp: 140, stamina: 102, vig: 52, mnd: 19, end: 27, str: 50, dex: 40, int: 15, fai: 15, arc: 10 },
    passive: { name: 'Sixth Sense', desc: 'Cheat death a single time. Effect replenishes at Sites of Grace or upon respawning.' },
    skill:   { name: 'Claw Shot', desc: 'Launches a grappling mechanism that pulls smaller enemies toward the user or draws the user toward larger foes.', cooldown: '8s' },
    ultimate:{ name: 'Onslaught Stake', desc: 'Powerful single attack that launches an iron stake with a great explosion. Can be charged for increased potency.' },
    startingEquipment: ["Wylder's Greatsword", "Wylder's Small Shield", "Wylder's Urn"],
  },
  guardian: {
    id: 'guardian',
    name: 'Guardian',
    description: 'A defensive powerhouse with a massive shield. Excels at protecting allies and absorbing damage.',
    image: null,
    scaling: { str: 'B', dex: 'C', int: 'D', fai: 'C', arc: 'C' },
    lvl1: { hp: 280, fp: 55, stamina: 60, vig: 10, mnd: 2, end: 6, str: 4, dex: 3, int: 2, fai: 3, arc: 10 },
    lvl15: { hp: 1280, fp: 115, stamina: 124, vig: 60, mnd: 14, end: 38, str: 39, dex: 29, int: 10, fai: 21, arc: 10 },
    passive: { name: 'Steel Guard', desc: 'Plant feet and brace with shield for more powerful guard. Multiplies shield Guard Boost by 5x, reducing stamina damage from blocking.' },
    skill:   { name: 'Whirlwind', desc: 'Beat wing to whip up a wind-churning cyclone. A 360-degree attack that can be charged for expanded area of effect.', cooldown: null },
    ultimate:{ name: 'Wings of Salvation', desc: 'Leap up and dive back down to raise protective area. Instantly resurrects nearby allies and grants damage immunity within the aura.' },
    startingEquipment: ["Guardian's Greatshield", "Guardian's Spear"],
  },
  ironeye: {
    id: 'ironeye',
    name: 'Ironeye',
    description: 'A precision ranged fighter with keen observation skills. Excels with bows and exploiting enemy weak points.',
    image: null,
    scaling: { str: 'C', dex: 'A', int: 'D', fai: 'D', arc: 'B' },
    lvl1: { hp: 200, fp: 55, stamina: 56, vig: 6, mnd: 2, end: 4, str: 4, dex: 8, int: 2, fai: 2, arc: 13 },
    lvl15: { hp: 820, fp: 115, stamina: 104, vig: 37, mnd: 14, end: 28, str: 19, dex: 57, int: 7, fai: 13, arc: 13 },
    passive: { name: 'Eagle Eye', desc: 'A keenly observant eye discovers more items to obtain from foes.' },
    skill:   { name: 'Marking', desc: 'Delivers a dagger strike that creates a temporary weak point on enemies, dealing additional damage. Teammates can exploit vulnerabilities.', cooldown: null },
    ultimate:{ name: 'Single Shot', desc: "Fires a powerful arrow that surpasses sound and ignores any defense, creating a shockwave that damages enemies in a large area." },
    startingEquipment: ["Ironeye's Longbow", "Ironeye's Dagger"],
  },
  duchess: {
    id: 'duchess',
    name: 'Duchess',
    description: 'A graceful hybrid fighter with exceptional dodge mechanics and the ability to replay past attacks.',
    image: null,
    scaling: { str: 'D', dex: 'B', int: 'A', fai: 'B', arc: 'C' },
    lvl1: { hp: 220, fp: 75, stamina: 54, vig: 7, mnd: 6, end: 3, str: 2, dex: 4, int: 4, fai: 3, arc: 11 },
    lvl15: { hp: 860, fp: 180, stamina: 84, vig: 39, mnd: 27, end: 18, str: 11, dex: 45, int: 42, fai: 27, arc: 11 },
    passive: { name: 'Magnificent Poise', desc: 'Attack and dodge optimally — allows a second dodge input when dodging repeatedly.' },
    skill:   { name: 'Restage', desc: 'Stage reprisal of recent occurrences to damage nearby foes — replicates 50% of damage inflicted in the last 3 seconds.', cooldown: null },
    ultimate:{ name: 'Finale', desc: 'Obscure self and surrounding allies to hide from foes for approximately 10 seconds.' },
    startingEquipment: ["Duchess's Rapier", "Duchess's Robe"],
  },
  raider: {
    id: 'raider',
    name: 'Raider',
    description: 'An unstoppable brawler with massive Strength scaling. Cannot be knocked down while using key abilities.',
    image: null,
    scaling: { str: 'S', dex: 'C', int: 'D', fai: 'D', arc: 'C' },
    lvl1: { hp: 260, fp: 55, stamina: 60, vig: 9, mnd: 2, end: 6, str: 9, dex: 4, int: 1, fai: 2, arc: 10 },
    lvl15: { hp: 1200, fp: 95, stamina: 122, vig: 56, mnd: 10, end: 37, str: 68, dex: 19, int: 3, fai: 12, arc: 10 },
    passive: { name: "Fighter's Resolve", desc: 'Taking damage boosts Retaliate potency. Cannot be knocked down while using Retaliate.' },
    skill:   { name: 'Retaliate', desc: 'Assume attack stance and pummel vigorously. Reduces damage taken when activated and performs powerful punches.', cooldown: null },
    ultimate:{ name: 'Totem Stela', desc: "Drive gravekeeper's wedge into earth to summon a giant tombstone. Provides protective auras and strength buffs to allies for 20 seconds." },
    startingEquipment: ["Raider's Flail", "Raider's Armor"],
  },
  recluse: {
    id: 'recluse',
    name: 'Recluse',
    description: 'A powerful dual-school spellcaster who collects elemental residues to fuel devastating magic cocktails.',
    image: null,
    scaling: { str: 'D', dex: 'C', int: 'S', fai: 'S', arc: 'C' },
    lvl1: { hp: 200, fp: 80, stamina: 54, vig: 6, mnd: 7, end: 3, str: 1, dex: 2, int: 5, fai: 5, arc: 10 },
    lvl15: { hp: 740, fp: 195, stamina: 94, vig: 33, mnd: 30, end: 23, str: 12, dex: 19, int: 51, fai: 51, arc: 10 },
    passive: { name: 'Residue Harvest', desc: 'Discover affinity residues that can be collected to replenish FP.' },
    skill:   { name: 'Affinity Cocktail', desc: 'Collect elemental residues to fire an affinity-exploiting magic cocktail with effects based on element combinations.', cooldown: null },
    ultimate:{ name: 'Soulblood Song', desc: 'Marks nearby enemies — when yourself or allies strike any of these enemies, they will regain HP and FP.' },
    startingEquipment: ["Recluse's Staff", "Recluse's Seal"],
  },
  executor: {
    id: 'executor',
    name: 'Executor',
    description: 'A cursed swordsman who excels at status ailment recovery and Sekiro-style deflection combat.',
    image: null,
    scaling: { str: 'C', dex: 'S', int: 'D', fai: 'D', arc: 'S' },
    lvl1: { hp: 220, fp: 55, stamina: 54, vig: 7, mnd: 2, end: 3, str: 5, dex: 8, int: 2, fai: 2, arc: 28 },
    lvl15: { hp: 1000, fp: 100, stamina: 102, vig: 46, mnd: 11, end: 27, str: 25, dex: 63, int: 8, fai: 6, arc: 28 },
    passive: { name: 'Ailment Recovery', desc: 'Receive boost after recovering from status ailments — provides attack power and stamina recovery for ~20 seconds.' },
    skill:   { name: 'Cursed Deflect', desc: 'Draw a cursed sword enabling deflection mechanics with a generous deflect window and negligible stamina consumption.', cooldown: null },
    ultimate:{ name: 'Beast Transformation', desc: 'Transform into a primordial beast form granting access to unique attacks and crowd control options for ~15 seconds.' },
    startingEquipment: ["Executor's Katana", "Executor's Mask"],
  },
  revenant: {
    id: 'revenant',
    name: 'Revenant',
    description: 'A necromancer who raises fallen enemies as allies and can make the entire party temporarily immortal.',
    image: null,
    scaling: { str: 'C', dex: 'C', int: 'B', fai: 'S', arc: 'B' },
    lvl1: { hp: 200, fp: 80, stamina: 54, vig: 6, mnd: 7, end: 3, str: 2, dex: 2, int: 4, fai: 5, arc: 12 },
    lvl15: { hp: 780, fp: 200, stamina: 90, vig: 35, mnd: 31, end: 21, str: 21, dex: 21, int: 30, fai: 51, arc: 12 },
    passive: { name: 'Necromancy', desc: 'Raise enemy ghosts to fight as allies — reanimates defeated foes as temporary phantom allies.' },
    skill:   { name: 'Summon Spirit', desc: 'Play lyre to summon fallen family to rally in battle — deploys one of three summons: Helen, Frederick, or Sebastian.', cooldown: null },
    ultimate:{ name: 'Immortal March', desc: 'Release vengeful ire to make self and nearby allies immortal for 15 seconds, preventing lethal damage and reviving downed teammates.' },
    startingEquipment: ["Revenant's Seal", "Revenant's Lyre"],
  },
  scholar: {
    id: 'scholar',
    name: 'Scholar',
    description: '(DLC - Forsaken Hollows) A specialist in Arcane who leverages unique knowledge-based abilities.',
    image: null,
    isDLC: true,
    scaling: { str: 'D', dex: 'C', int: 'C', fai: 'C', arc: 'S' },
    lvl1: { hp: 220, fp: 65, stamina: 54, vig: 7, mnd: 5, end: 3, str: 2, dex: 3, int: 4, fai: 4, arc: 15 },
    lvl15: { hp: 900, fp: 155, stamina: 90, vig: 42, mnd: 22, end: 22, str: 12, dex: 18, int: 20, fai: 20, arc: 45 },
    passive: { name: 'Scholar Passive', desc: 'Details not yet confirmed — DLC character.' },
    skill:   { name: 'Scholar Skill', desc: 'Details not yet confirmed — DLC character.', cooldown: null },
    ultimate:{ name: 'Scholar Ultimate', desc: 'Details not yet confirmed — DLC character.' },
    startingEquipment: ["Scholar's Tome"],
  },
  undertaker: {
    id: 'undertaker',
    name: 'Undertaker',
    description: '(DLC - Forsaken Hollows) A Strength/Faith hybrid focused on powerful weapon arts.',
    image: null,
    isDLC: true,
    scaling: { str: 'A', dex: 'D', int: 'D', fai: 'A', arc: 'C' },
    lvl1: { hp: 220, fp: 65, stamina: 54, vig: 7, mnd: 5, end: 3, str: 7, dex: 2, int: 2, fai: 7, arc: 10 },
    lvl15: { hp: 980, fp: 140, stamina: 100, vig: 45, mnd: 19, end: 24, str: 50, dex: 12, int: 8, fai: 50, arc: 10 },
    passive: { name: 'Undertaker Passive', desc: 'Details not yet confirmed — DLC character.' },
    skill:   { name: 'Undertaker Skill', desc: 'Details not yet confirmed — DLC character.', cooldown: null },
    ultimate:{ name: 'Undertaker Ultimate', desc: 'Details not yet confirmed — DLC character.' },
    startingEquipment: ["Undertaker's Sword"],
  },
};

// Talisman data (up to 2 equipped)
const TALISMANS = [
  { id: 'ancestral_horn', name: "Ancestral Spirit's Horn", effects: [{ stat: 'fpOnKill', type: 'percent', value: 5, label: 'FP on kill +5%' }] },
  { id: 'arrows_reach', name: "Arrow's Reach Talisman", effects: [{ stat: 'projectileRange', type: 'percent', value: 100, label: 'Projectile range +100%' }] },
  { id: 'arrows_sting', name: "Arrow's Sting Talisman", effects: [{ stat: 'rangedAtk', type: 'percent', value: 14, label: 'Ranged attack +14%' }] },
  { id: 'assassins_cerulean', name: "Assassin's Cerulean Dagger", effects: [{ stat: 'fp', type: 'onCritical', value: 10, label: 'Critical hit FP restore +10%' }] },
  { id: 'assassins_crimson', name: "Assassin's Crimson Dagger", effects: [{ stat: 'hp', type: 'onCritical', value: 18, label: 'Critical hit HP restore +18%' }] },
  { id: 'axe_talisman', name: 'Axe Talisman', effects: [{ stat: 'chargeAtk', type: 'percent', value: 12, label: 'Charged attack +12%' }] },
  { id: 'blessed_dew', name: 'Blessed Dew Talisman', effects: [{ stat: 'hpRegen', type: 'flat', value: 2, label: 'HP regen +2/s' }] },
  { id: 'blue_feather', name: 'Blue-Feathered Branchsword', effects: [{ stat: 'damageNeg', type: 'lowHp', value: 50, label: 'Damage negation at low HP +50%' }] },
  { id: 'boltdrake', name: 'Boltdrake Talisman', effects: [{ stat: 'lightningNeg', type: 'percent', value: 20, label: 'Lightning negation +20%' }] },
  { id: 'bull_goat', name: "Bull-Goat's Talisman", effects: [{ stat: 'poise', type: 'percent', value: 25, label: 'Poise +25%' }] },
  { id: 'carian_crest', name: 'Carian Filigreed Crest', effects: [{ stat: 'skillFpCost', type: 'percent', value: -25, label: 'Skill FP cost -25%' }] },
  { id: 'cerulean_amber', name: 'Cerulean Amber Medallion', effects: [{ stat: 'fp', type: 'percent', value: 12, label: 'Max FP +12%' }] },
  { id: 'claw_talisman', name: 'Claw Talisman', effects: [{ stat: 'jumpAtk', type: 'percent', value: 12, label: 'Jump attack +12%' }] },
  { id: 'crimson_amber', name: 'Crimson Amber Medallion', effects: [{ stat: 'hp', type: 'percent', value: 12, label: 'Max HP +12%' }] },
  { id: 'crimson_seed', name: 'Crimson Seed Talisman', effects: [{ stat: 'flaskHp', type: 'percent', value: 20, label: 'Flask HP restoration +20%' }] },
  { id: 'crucible_feather', name: 'Crucible Feather Talisman', effects: [{ stat: 'dodge', type: 'improve', value: 1, label: 'Improved dodging' }, { stat: 'damageNeg', type: 'percent', value: -10, label: 'Damage negation -10%' }] },
  { id: 'dagger_talisman', name: 'Dagger Talisman', effects: [{ stat: 'criticalAtk', type: 'percent', value: 24, label: 'Critical hits +24%' }] },
  { id: 'dragoncrest_shield', name: 'Dragoncrest Shield Talisman', effects: [{ stat: 'physNeg', type: 'percent', value: 15, label: 'Physical negation +15%' }] },
  { id: 'erdtrees_favor', name: "Erdtree's Favor", effects: [{ stat: 'hp', type: 'percent', value: 7, label: 'Max HP +7%' }, { stat: 'stamina', type: 'percent', value: 7, label: 'Max Stamina +7%' }] },
  { id: 'faithful_canvas', name: "Faithful's Canvas Talisman", effects: [{ stat: 'incantations', type: 'percent', value: 11, label: 'Incantation power +11%' }] },
  { id: 'fire_scorpion', name: 'Fire Scorpion Charm', effects: [{ stat: 'fireAtk', type: 'percent', value: 15, label: 'Fire attack +15%' }, { stat: 'physNeg', type: 'percent', value: -3, label: 'Physical negation -3%' }] },
  { id: 'flamedrake', name: 'Flamedrake Talisman', effects: [{ stat: 'fireNeg', type: 'percent', value: 20, label: 'Fire negation +20%' }] },
  { id: 'godfrey_icon', name: 'Godfrey Icon', effects: [{ stat: 'chargedSpells', type: 'percent', value: 18, label: 'Charged spells & skills +18%' }] },
  { id: 'godskin_cloth', name: 'Godskin Swaddling Cloth', effects: [{ stat: 'hp', type: 'onSuccessive', value: 6, label: 'HP restore on successive attacks +6%' }] },
  { id: 'gold_scarab', name: 'Gold Scarab', effects: [{ stat: 'runes', type: 'percent', value: 15, label: 'Rune gain +15%' }] },
  { id: 'graven_school', name: 'Graven-School Talisman', effects: [{ stat: 'sorceries', type: 'percent', value: 11, label: 'Sorcery power +11%' }] },
  { id: 'greatshield_talisman', name: 'Greatshield Talisman', effects: [{ stat: 'guardAbility', type: 'percent', value: 20, label: 'Guard ability +20%' }] },
  { id: 'green_turtle', name: 'Green Turtle Talisman', effects: [{ stat: 'staminaRegen', type: 'flat', value: 8, label: 'Stamina regen +8/s' }] },
  { id: 'haligdrake', name: 'Haligdrake Talisman', effects: [{ stat: 'holyNeg', type: 'percent', value: 20, label: 'Holy negation +20%' }] },
  { id: 'kindred_rot', name: "Kindred of Rot's Exultation", effects: [{ stat: 'atkPower', type: 'onStatusNearby', value: 20, label: 'Attack power +20% on poison/rot nearby' }] },
  { id: 'lightning_scorpion', name: 'Lightning Scorpion Charm', effects: [{ stat: 'lightningAtk', type: 'percent', value: 15, label: 'Lightning attack +15%' }, { stat: 'physNeg', type: 'percent', value: -3, label: 'Physical negation -3%' }] },
  { id: 'lord_of_blood', name: "Lord of Blood's Exultation", effects: [{ stat: 'atkPower', type: 'onBloodloss', value: 20, label: 'Attack power +20% on bloodloss' }] },
  { id: 'magic_scorpion', name: 'Magic Scorpion Charm', effects: [{ stat: 'magicAtk', type: 'percent', value: 15, label: 'Magic attack +15%' }, { stat: 'physNeg', type: 'percent', value: -3, label: 'Physical negation -3%' }] },
  { id: 'millicent', name: "Millicent's Prosthesis", effects: [{ stat: 'dex', type: 'percent', value: 5, label: 'Dex +5%' }] },
  { id: 'mottled_necklace', name: 'Mottled Necklace', effects: [{ stat: 'statusRes', type: 'flat', value: 40, label: 'All status resistances +40' }] },
  { id: 'old_lords', name: "Old Lord's Talisman", effects: [{ stat: 'spellDuration', type: 'percent', value: 30, label: 'Spell duration +30%' }] },
  { id: 'pearldrake', name: 'Pearldrake Talisman', effects: [{ stat: 'nonPhysNeg', type: 'percent', value: 10, label: 'Non-physical negation +10%' }] },
  { id: 'primal_glintstone', name: 'Primal Glintstone Blade', effects: [{ stat: 'spellFpCost', type: 'flat', value: -25, label: 'Spell FP cost -25' }, { stat: 'hp', type: 'percent', value: -15, label: 'Max HP -15%' }] },
  { id: 'radagon_icon', name: 'Radagon Icon', effects: [{ stat: 'spellSpeed', type: 'flat', value: 60, label: 'Spell cast speed +60' }] },
  { id: 'red_feather', name: 'Red-Feathered Branchsword', effects: [{ stat: 'atkPower', type: 'lowHp', value: 20, label: 'Attack power at low HP +20%' }] },
  { id: 'ritual_shield', name: 'Ritual Shield Talisman', effects: [{ stat: 'damageNeg', type: 'fullHp', value: 30, label: 'Damage negation at full HP +30%' }] },
  { id: 'ritual_sword', name: 'Ritual Sword Talisman', effects: [{ stat: 'atkPower', type: 'fullHp', value: 10, label: 'Attack power at full HP +10%' }] },
  { id: 'roar_medallion', name: 'Roar Medallion', effects: [{ stat: 'roarAtk', type: 'percent', value: 20, label: 'Roar/Breath attacks +20%' }] },
  { id: 'sacred_scorpion', name: 'Sacred Scorpion Charm', effects: [{ stat: 'holyAtk', type: 'percent', value: 15, label: 'Holy attack +15%' }, { stat: 'physNeg', type: 'percent', value: -3, label: 'Physical negation -3%' }] },
  { id: 'sacrificial_twig', name: 'Sacrificial Twig', effects: [{ stat: 'noRuneLoss', type: 'special', value: 1, label: 'No rune loss on death' }] },
  { id: 'silver_scarab', name: 'Silver Scarab', effects: [{ stat: 'itemDiscovery', type: 'flat', value: 40, label: 'Item discovery +40' }] },
  { id: 'spear_talisman', name: 'Spear Talisman', effects: [{ stat: 'thrustCounter', type: 'percent', value: 20, label: 'Thrusting counterattack +20%' }] },
  { id: 'spelldrake', name: 'Spelldrake Talisman', effects: [{ stat: 'magicNeg', type: 'percent', value: 20, label: 'Magic negation +20%' }] },
  { id: 'takers_cameo', name: "Taker's Cameo", effects: [{ stat: 'hp', type: 'onKill', value: 6, label: 'HP restore on kill +6%' }] },
  { id: 'twinblade_talisman', name: 'Twinblade Talisman', effects: [{ stat: 'chainFinisher', type: 'percent', value: 15, label: 'Chain attack finishers +15%' }] },
  { id: 'viridian_amber', name: 'Viridian Amber Medallion', effects: [{ stat: 'stamina', type: 'percent', value: 12, label: 'Max Stamina +12%' }] },
  { id: 'warrior_jar', name: 'Warrior Jar Shard', effects: [{ stat: 'skillAtk', type: 'percent', value: 15, label: 'Skill attack power +15%' }] },
  { id: 'winged_sword', name: 'Winged Sword Insignia', effects: [{ stat: 'atkPower', type: 'successive', value: 1, label: 'Attack power stacks on successive hits' }] },
  { id: 'curved_sword', name: 'Curved Sword Talisman', effects: [{ stat: 'guardCounter', type: 'percent', value: 20, label: 'Guard counters +20%' }] },
  { id: 'companion_jar', name: 'Companion Jar', effects: [{ stat: 'throwingPots', type: 'percent', value: 20, label: 'Throwing pots +20%' }] },
  { id: 'hammer_talisman', name: 'Hammer Talisman', effects: [{ stat: 'guardBreak', type: 'percent', value: 50, label: 'Guard breaking +50%' }] },
];

// Relic effects — standard (available in both regular and Deep of Night)
const RELIC_EFFECTS_STANDARD = [
  // ── Elemental Damage ──
  { id: 'phys_dmg_1', label: 'Physical Damage +4%', stat: 'physAtk', type: 'percent', value: 4 },
  { id: 'phys_dmg_2', label: 'Physical Damage +5%', stat: 'physAtk', type: 'percent', value: 5 },
  { id: 'phys_dmg_3', label: 'Physical Damage +6%', stat: 'physAtk', type: 'percent', value: 6 },
  { id: 'fire_dmg_1', label: 'Fire Damage +4.5%', stat: 'fireAtk', type: 'percent', value: 4.5 },
  { id: 'fire_dmg_2', label: 'Fire Damage +5.5%', stat: 'fireAtk', type: 'percent', value: 5.5 },
  { id: 'fire_dmg_3', label: 'Fire Damage +6.5%', stat: 'fireAtk', type: 'percent', value: 6.5 },
  { id: 'fire_dmg_4', label: 'Fire Damage +8.5%', stat: 'fireAtk', type: 'percent', value: 8.5 },
  { id: 'magic_dmg_1', label: 'Magic Damage +4.5%', stat: 'magicAtk', type: 'percent', value: 4.5 },
  { id: 'magic_dmg_2', label: 'Magic Damage +5.5%', stat: 'magicAtk', type: 'percent', value: 5.5 },
  { id: 'magic_dmg_3', label: 'Magic Damage +6.5%', stat: 'magicAtk', type: 'percent', value: 6.5 },
  { id: 'lightning_dmg_1', label: 'Lightning Damage +4.5%', stat: 'lightningAtk', type: 'percent', value: 4.5 },
  { id: 'lightning_dmg_2', label: 'Lightning Damage +5.5%', stat: 'lightningAtk', type: 'percent', value: 5.5 },
  { id: 'lightning_dmg_3', label: 'Lightning Damage +6.5%', stat: 'lightningAtk', type: 'percent', value: 6.5 },
  { id: 'holy_dmg_1', label: 'Holy Damage +6.5%', stat: 'holyAtk', type: 'percent', value: 6.5 },
  // ── Sorceries & Incantations ──
  { id: 'sorcery_1', label: 'Improved Sorceries (1.05x)', stat: 'magicAtk', type: 'multiplier', value: 1.05 },
  { id: 'sorcery_2', label: 'Improved Sorceries (1.085x)', stat: 'magicAtk', type: 'multiplier', value: 1.085 },
  { id: 'sorcery_3', label: 'Improved Sorceries (1.1x)', stat: 'magicAtk', type: 'multiplier', value: 1.1 },
  { id: 'incant_1', label: 'Improved Incantations (1.05x)', stat: 'holyAtk', type: 'multiplier', value: 1.05 },
  { id: 'incant_2', label: 'Improved Incantations (1.085x)', stat: 'holyAtk', type: 'multiplier', value: 1.085 },
  { id: 'incant_3', label: 'Improved Incantations (1.1x)', stat: 'holyAtk', type: 'multiplier', value: 1.1 },
  { id: 'spell_duration', label: 'Extend Spell Duration +50%', stat: 'spellDuration', type: 'special', value: 50 },
  // ── Critical & Counter ──
  { id: 'crit_dmg_1', label: 'Critical Hit Damage +18%', stat: 'criticalAtk', type: 'percent', value: 18 },
  { id: 'crit_dmg_2', label: 'Critical Hit Damage +23%', stat: 'criticalAtk', type: 'percent', value: 23 },
  { id: 'guard_counter_1', label: 'Guard Counter Damage +18%', stat: 'guardCounter', type: 'percent', value: 18 },
  { id: 'guard_counter_2', label: 'Guard Counter (1.25x)', stat: 'guardCounter', type: 'multiplier', value: 1.25 },
  { id: 'guard_counter_3', label: 'Guard Counter (1.29x)', stat: 'guardCounter', type: 'multiplier', value: 1.29 },
  // ── Weapon Type ──
  { id: 'weapon_type_atk', label: 'Weapon Type Attack +9%', stat: 'physAtk', type: 'percent', value: 9 },
  { id: 'throwing_knife', label: 'Throwing Knife Damage +15%', stat: 'rangedAtk', type: 'percent', value: 15 },
  { id: 'throwing_pot', label: 'Throwing Pot Damage +15%', stat: 'rangedAtk', type: 'percent', value: 15 },
  { id: 'roar_breath', label: 'Roar & Breath Attacks +15%', stat: 'roarAtk', type: 'percent', value: 15 },
  // ── Skill & Ultimate ──
  { id: 'art_gauge_kill', label: 'Art Gauge +5% per Kill', stat: 'ultimateAtk', type: 'special', value: 5 },
  { id: 'art_gauge_fill_1', label: 'Art Gauge Fill +5%', stat: 'ultimateAtk', type: 'percent', value: 5 },
  { id: 'art_gauge_fill_2', label: 'Art Gauge Fill +7.5%', stat: 'ultimateAtk', type: 'percent', value: 7.5 },
  { id: 'art_gauge_fill_3', label: 'Art Gauge Fill +10%', stat: 'ultimateAtk', type: 'percent', value: 10 },
  { id: 'skill_atk', label: 'Skill Attack Power +10%', stat: 'skillAtk', type: 'percent', value: 10 },
  { id: 'skill_cooldown', label: 'Skill Cooldown -15%', stat: 'cooldown', type: 'percent', value: -15 },
  // ── Resources ──
  { id: 'max_hp', label: 'Max HP +100', stat: 'hp', type: 'flat', value: 100 },
  { id: 'max_fp', label: 'Max FP +25', stat: 'fp', type: 'flat', value: 25 },
  { id: 'max_stamina', label: 'Max Stamina +10', stat: 'stamina', type: 'flat', value: 10 },
  { id: 'hp_regen', label: 'Continuous HP Recovery +1/s', stat: 'hpRegen', type: 'flat', value: 1 },
  { id: 'fp_regen', label: 'FP Restoration on Attack +1', stat: 'fpRegen', type: 'flat', value: 1 },
  { id: 'stamina_regen_atk', label: 'Stamina on Attack +2', stat: 'staminaRegen', type: 'flat', value: 2 },
  { id: 'stamina_regen_atk2', label: 'Stamina on Attack +3', stat: 'staminaRegen', type: 'flat', value: 3 },
  { id: 'hp_on_guard', label: 'HP on Guard +8', stat: 'hpRegen', type: 'special', value: 8 },
  { id: 'hp_on_weapon_atk', label: 'HP on Weapon Attack +10', stat: 'hpRegen', type: 'special', value: 10 },
  { id: 'hp_on_counter', label: 'HP on Thrusting Counter +2.5%', stat: 'hpRegen', type: 'special', value: 2.5 },
  // ── Damage Negation ──
  { id: 'phys_neg_1', label: 'Physical Negation +10%', stat: 'physNeg', type: 'percent', value: 10 },
  { id: 'phys_neg_2', label: 'Physical Negation +10.5%', stat: 'physNeg', type: 'percent', value: 10.5 },
  { id: 'phys_neg_3', label: 'Physical Negation +12%', stat: 'physNeg', type: 'percent', value: 12 },
  { id: 'fire_neg_1', label: 'Fire Negation +10%', stat: 'fireNeg', type: 'percent', value: 10 },
  { id: 'fire_neg_2', label: 'Fire Negation +15%', stat: 'fireNeg', type: 'percent', value: 15 },
  { id: 'fire_neg_3', label: 'Fire Negation +16%', stat: 'fireNeg', type: 'percent', value: 16 },
  { id: 'magic_neg_1', label: 'Magic Negation +10%', stat: 'magicNeg', type: 'percent', value: 10 },
  { id: 'magic_neg_2', label: 'Magic Negation +15%', stat: 'magicNeg', type: 'percent', value: 15 },
  { id: 'magic_neg_3', label: 'Magic Negation +16%', stat: 'magicNeg', type: 'percent', value: 16 },
  { id: 'lightning_neg_1', label: 'Lightning Negation +10%', stat: 'lightningNeg', type: 'percent', value: 10 },
  { id: 'lightning_neg_2', label: 'Lightning Negation +15%', stat: 'lightningNeg', type: 'percent', value: 15 },
  { id: 'lightning_neg_3', label: 'Lightning Negation +16%', stat: 'lightningNeg', type: 'percent', value: 16 },
  { id: 'holy_neg_1', label: 'Holy Negation +10%', stat: 'holyNeg', type: 'percent', value: 10 },
  { id: 'holy_neg_2', label: 'Holy Negation +15%', stat: 'holyNeg', type: 'percent', value: 15 },
  { id: 'holy_neg_3', label: 'Holy Negation +16%', stat: 'holyNeg', type: 'percent', value: 16 },
  { id: 'affinity_neg_1', label: 'All Elemental Negation +10.5%', stat: 'nonPhysNeg', type: 'percent', value: 10.5 },
  { id: 'affinity_neg_2', label: 'All Elemental Negation +12%', stat: 'nonPhysNeg', type: 'percent', value: 12 },
  { id: 'low_hp_neg', label: 'Dmg Negation at Low HP +25%', stat: 'allNeg', type: 'special', value: 25 },
  // ── Poise ──
  { id: 'poise_1', label: 'Poise +1 (Stance Dmg -5%)', stat: 'poise', type: 'percent', value: 5 },
  { id: 'poise_2', label: 'Poise +2 (Stance Dmg -10%)', stat: 'poise', type: 'percent', value: 10 },
  { id: 'poise_3', label: 'Poise +3 (Stance Dmg -15%)', stat: 'poise', type: 'percent', value: 15 },
  // ── Attributes ──
  { id: 'vigor_1', label: 'Vigor +1 (HP +20)', stat: 'hp', type: 'flat', value: 20 },
  { id: 'vigor_2', label: 'Vigor +2 (HP +40)', stat: 'hp', type: 'flat', value: 40 },
  { id: 'vigor_3', label: 'Vigor +3 (HP +60)', stat: 'hp', type: 'flat', value: 60 },
  { id: 'mind_1', label: 'Mind +1 (FP +5)', stat: 'fp', type: 'flat', value: 5 },
  { id: 'mind_2', label: 'Mind +2 (FP +10)', stat: 'fp', type: 'flat', value: 10 },
  { id: 'mind_3', label: 'Mind +3 (FP +15)', stat: 'fp', type: 'flat', value: 15 },
  { id: 'end_1', label: 'Endurance +1 (Stamina +2)', stat: 'stamina', type: 'flat', value: 2 },
  { id: 'end_2', label: 'Endurance +2 (Stamina +4)', stat: 'stamina', type: 'flat', value: 4 },
  { id: 'end_3', label: 'Endurance +3 (Stamina +6)', stat: 'stamina', type: 'flat', value: 6 },
  // ── Status Resistance ──
  { id: 'poison_res', label: 'Poison Resistance +110', stat: 'poisonRes', type: 'flat', value: 110 },
  { id: 'bleed_res', label: 'Blood Loss Resistance +110', stat: 'bleedRes', type: 'flat', value: 110 },
  { id: 'frost_res', label: 'Frost Resistance +110', stat: 'frostRes', type: 'flat', value: 110 },
  { id: 'status_res_all', label: 'All Status Resistance +130', stat: 'statusRes', type: 'flat', value: 130 },
  // ── Utility ──
  { id: 'fp_cost_1', label: 'FP Consumption (0.92x)', stat: 'skillFpCost', type: 'multiplier', value: 0.92 },
  { id: 'fp_cost_2', label: 'FP Consumption (0.87x)', stat: 'skillFpCost', type: 'multiplier', value: 0.87 },
  { id: 'fp_cost_3', label: 'FP Consumption (0.84x)', stat: 'skillFpCost', type: 'multiplier', value: 0.84 },
  { id: 'item_discovery', label: 'Item Discovery +20', stat: 'itemDiscovery', type: 'flat', value: 20 },
  { id: 'rune_gain', label: 'Rune Gain +10%', stat: 'runes', type: 'percent', value: 10 },
  { id: 'rune_crit', label: 'Runes +300 on Critical Hit', stat: 'runes', type: 'special', value: 300 },
  { id: 'flask_ally', label: 'Flask Heals Allies (50%)', stat: 'flaskAlly', type: 'special', value: 50 },
  // ── Conditional Offensive ──
  { id: 'atk_vs_poison', label: 'Attack +10% vs Poisoned', stat: 'physAtk', type: 'special', value: 10 },
  { id: 'atk_vs_frost', label: 'Attack +10% vs Frostbitten', stat: 'physAtk', type: 'special', value: 10 },
  { id: 'atk_vs_rot', label: 'Attack +10% vs Scarlet Rot', stat: 'physAtk', type: 'special', value: 10 },
  { id: 'atk_after_hit', label: 'Attack +15% for 10s After Hit', stat: 'physAtk', type: 'special', value: 15 },
  { id: 'atk_weapon_switch', label: 'Attack +10% on Weapon Switch', stat: 'physAtk', type: 'special', value: 10 },
  { id: 'atk_grease', label: 'Attack +10% After Grease (30s)', stat: 'physAtk', type: 'special', value: 10 },
  // ── Charge Attack Procs ──
  { id: 'charge_black_flame', label: 'Charge Atk: Black Flames', stat: 'chargeProc', type: 'special', value: 1 },
  { id: 'charge_ice', label: 'Charge Atk: Ice Storm', stat: 'chargeProc', type: 'special', value: 1 },
  { id: 'charge_lightning', label: 'Charge Atk: Lightning', stat: 'chargeProc', type: 'special', value: 1 },
  { id: 'charge_holy', label: 'Charge Atk: Holy Shockwave', stat: 'chargeProc', type: 'special', value: 1 },
  { id: 'charge_magma', label: 'Charge Atk: Magma', stat: 'chargeProc', type: 'special', value: 1 },
  { id: 'charge_sleep', label: 'Charge Atk: Sleep Mist', stat: 'chargeProc', type: 'special', value: 1 },
  // ── Attack Procs ──
  { id: 'atk_wraiths', label: 'Attacks Summon Wraiths', stat: 'atkProc', type: 'special', value: 1 },
  { id: 'atk_spirits', label: 'Attacks Call Vengeful Spirits', stat: 'atkProc', type: 'special', value: 1 },
  { id: 'atk_lava', label: 'Attacks Generate Lava', stat: 'atkProc', type: 'special', value: 1 },
  { id: 'atk_charm', label: 'Attacks Release Charm Mist', stat: 'atkProc', type: 'special', value: 1 },
  { id: 'atk_frost_mist', label: 'Attacks Release Frost Mist', stat: 'atkProc', type: 'special', value: 1 },
  { id: 'atk_lightning', label: 'Attacks Unleash Lightning', stat: 'atkProc', type: 'special', value: 1 },
  { id: 'atk_golden_shock', label: 'Attacks: Golden Shockwave', stat: 'atkProc', type: 'special', value: 1 },
  { id: 'instant_death', label: 'Rare Instant Kill Chance', stat: 'atkProc', type: 'special', value: 1 },
  // ── Starting Armament Affinity ──
  { id: 'start_fire', label: 'Starting Armament: Fire', stat: 'startAffinity', type: 'special', value: 1 },
  { id: 'start_magic', label: 'Starting Armament: Magic', stat: 'startAffinity', type: 'special', value: 1 },
  { id: 'start_lightning', label: 'Starting Armament: Lightning', stat: 'startAffinity', type: 'special', value: 1 },
  { id: 'start_holy', label: 'Starting Armament: Holy', stat: 'startAffinity', type: 'special', value: 1 },
];

// Deep of Night exclusive effects (only available with Deep toggle on)
const RELIC_EFFECTS_DEEP = [
  { id: 'deep_crit_hp', label: '[Deep] Critical Hit HP Restore', stat: 'hpRegen', type: 'special', value: 1 },
  { id: 'deep_crit_fp', label: '[Deep] Critical Hit FP Restore', stat: 'fpRegen', type: 'special', value: 1 },
  { id: 'deep_guard_hp', label: '[Deep] HP Recovery on Guard', stat: 'hpRegen', type: 'special', value: 1 },
  { id: 'deep_guard_fp', label: '[Deep] FP Recovery on Guard', stat: 'fpRegen', type: 'special', value: 1 },
  { id: 'deep_stamina_rec', label: '[Deep] Improved Stamina Recovery', stat: 'staminaRegen', type: 'flat', value: 5 },
  { id: 'deep_phys_neg', label: '[Deep] Improved Phys. Negation', stat: 'physNeg', type: 'percent', value: 14 },
  { id: 'deep_affinity_neg', label: '[Deep] Improved Elemental Neg.', stat: 'nonPhysNeg', type: 'percent', value: 14 },
  { id: 'deep_flask', label: '[Deep] Improved Flask (1.1x)', stat: 'flaskHp', type: 'multiplier', value: 1.1 },
  { id: 'deep_flask_gradual', label: '[Deep] Flask Gradual Restore', stat: 'hpRegen', type: 'special', value: 1 },
  { id: 'deep_stance_break', label: '[Deep] Improved Stance-Breaking', stat: 'stanceBreak', type: 'special', value: 1 },
  { id: 'deep_thrust_counter', label: '[Deep] Improved Thrust Counter', stat: 'thrustCounter', type: 'special', value: 1 },
  { id: 'deep_despair', label: '[Deep] Power of Despair (Instant Kill)', stat: 'atkProc', type: 'special', value: 1 },
  { id: 'deep_ancestral', label: '[Deep] Ancestral Spirit (Neg. Reduce)', stat: 'atkProc', type: 'special', value: 1 },
  { id: 'deep_endure', label: '[Deep] Stance Break → Endure', stat: 'poise', type: 'special', value: 1 },
  { id: 'deep_holy_ground', label: '[Deep] Holy Ground at Low HP', stat: 'hpRegen', type: 'special', value: 1 },
  { id: 'deep_parry_golden', label: '[Deep] Parry → Golden Retaliation', stat: 'atkProc', type: 'special', value: 1 },
  { id: 'deep_guard_holy', label: '[Deep] Guard Counter → Holy Attack', stat: 'holyAtk', type: 'special', value: 1 },
  { id: 'deep_bleed_buildup', label: '[Deep] Attacks Build Blood Loss', stat: 'atkProc', type: 'special', value: 1 },
  { id: 'deep_charge_proj', label: '[Deep] Charge Atk: Projectiles', stat: 'chargeProc', type: 'special', value: 1 },
];

// Combined getter — returns available effects based on Deep of Night toggle
function getRelicEffects(deepOfNight) {
  if (deepOfNight) {
    return [...RELIC_EFFECTS_STANDARD, ...RELIC_EFFECTS_DEEP];
  }
  return RELIC_EFFECTS_STANDARD;
}

// Legacy compat
const RELIC_EFFECTS = RELIC_EFFECTS_STANDARD;

// Relic scene types by slot color
const RELIC_SCENES = {
  red:    { name: 'Burning Scene',   desc: 'Red relics — offensive / fire-aligned' },
  green:  { name: 'Tranquil Scene',  desc: 'Green relics — healing / nature-aligned' },
  blue:   { name: 'Drizzly Scene',   desc: 'Blue relics — magic / water-aligned' },
  yellow: { name: 'Luminous Scene',  desc: 'Yellow relics — holy / lightning-aligned' },
  white:  { name: 'Universal',       desc: 'Accepts any relic type' },
};

// Max relics per slot (Delicate=1, Polished=2, Grand=3 effects)
const RELIC_TIERS = [
  { id: 'delicate', name: 'Delicate', effects: 1 },
  { id: 'polished', name: 'Polished', effects: 2 },
  { id: 'grand', name: 'Grand', effects: 3 },
];

// Vessel data per character
const VESSELS = {
  wylder: [
    { id: 'wylder_urn',        name: "Wylder's Urn",              slots: ['red', 'yellow', 'yellow'] },
    { id: 'wylder_goblet',     name: "Wylder's Goblet",           slots: ['red', 'blue', 'green'] },
    { id: 'wylder_chalice',    name: "Wylder's Chalice",          slots: ['blue', 'yellow', 'white'] },
    { id: 'wylder_soot',       name: "Soot-Covered Wylder's Urn", slots: ['red', 'red', 'blue'] },
    { id: 'wylder_sealed',     name: "Sealed Wylder's Urn",       slots: ['yellow', 'yellow', 'red'] },
  ],
  guardian: [
    { id: 'guardian_urn',      name: "Guardian's Urn",              slots: ['red', 'yellow', 'yellow'] },
    { id: 'guardian_goblet',   name: "Guardian's Goblet",           slots: ['blue', 'blue', 'green'] },
    { id: 'guardian_chalice',  name: "Guardian's Chalice",          slots: ['blue', 'yellow', 'white'] },
    { id: 'guardian_soot',     name: "Soot-Covered Guardian's Urn", slots: ['red', 'green', 'green'] },
    { id: 'guardian_sealed',   name: "Sealed Guardian's Urn",       slots: ['yellow', 'yellow', 'red'] },
  ],
  ironeye: [
    { id: 'ironeye_urn',      name: "Ironeye's Urn",              slots: ['yellow', 'green', 'green'] },
    { id: 'ironeye_goblet',   name: "Ironeye's Goblet",           slots: ['red', 'blue', 'yellow'] },
    { id: 'ironeye_chalice',  name: "Ironeye's Chalice",          slots: ['red', 'green', 'white'] },
    { id: 'ironeye_soot',     name: "Soot-Covered Ironeye's Urn", slots: ['blue', 'yellow', 'yellow'] },
    { id: 'ironeye_sealed',   name: "Sealed Ironeye's Urn",       slots: ['green', 'green', 'yellow'] },
  ],
  duchess: [
    { id: 'duchess_urn',      name: "Duchess' Urn",              slots: ['red', 'blue', 'blue'] },
    { id: 'duchess_goblet',   name: "Duchess' Goblet",           slots: ['yellow', 'yellow', 'green'] },
    { id: 'duchess_chalice',  name: "Duchess' Chalice",          slots: ['blue', 'yellow', 'white'] },
    { id: 'duchess_soot',     name: "Soot-Covered Duchess' Urn", slots: ['red', 'red', 'green'] },
    { id: 'duchess_sealed',   name: "Sealed Duchess' Urn",       slots: ['blue', 'blue', 'red'] },
  ],
  raider: [
    { id: 'raider_urn',      name: "Raider's Urn",              slots: ['red', 'green', 'green'] },
    { id: 'raider_goblet',   name: "Raider's Goblet",           slots: ['red', 'blue', 'yellow'] },
    { id: 'raider_chalice',  name: "Raider's Chalice",          slots: ['red', 'red', 'white'] },
    { id: 'raider_soot',     name: "Soot-Covered Raider's Urn", slots: ['blue', 'blue', 'green'] },
    { id: 'raider_sealed',   name: "Sealed Raider's Urn",       slots: ['green', 'green', 'red'] },
  ],
  recluse: [
    { id: 'recluse_urn',      name: "Recluse's Urn",              slots: ['blue', 'green', 'green'] },
    { id: 'recluse_goblet',   name: "Recluse's Goblet",           slots: ['red', 'blue', 'yellow'] },
    { id: 'recluse_chalice',  name: "Recluse's Chalice",          slots: ['yellow', 'green', 'white'] },
    { id: 'recluse_soot',     name: "Soot-Covered Recluse's Urn", slots: ['red', 'red', 'green'] },
    { id: 'recluse_sealed',   name: "Sealed Recluse's Urn",       slots: ['green', 'green', 'red'] },
  ],
  executor: [
    { id: 'executor_urn',      name: "Executor's Urn",              slots: ['red', 'yellow', 'yellow'] },
    { id: 'executor_goblet',   name: "Executor's Goblet",           slots: ['red', 'blue', 'green'] },
    { id: 'executor_chalice',  name: "Executor's Chalice",          slots: ['blue', 'yellow', 'white'] },
    { id: 'executor_soot',     name: "Soot-Covered Executor's Urn", slots: ['red', 'red', 'blue'] },
    { id: 'executor_sealed',   name: "Sealed Executor's Urn",       slots: ['yellow', 'yellow', 'red'] },
  ],
  revenant: [
    { id: 'revenant_urn',      name: "Revenant's Urn",              slots: ['red', 'yellow', 'yellow'] },
    { id: 'revenant_goblet',   name: "Revenant's Goblet",           slots: ['red', 'blue', 'green'] },
    { id: 'revenant_chalice',  name: "Revenant's Chalice",          slots: ['blue', 'yellow', 'white'] },
    { id: 'revenant_soot',     name: "Soot-Covered Revenant's Urn", slots: ['red', 'red', 'blue'] },
    { id: 'revenant_sealed',   name: "Sealed Revenant's Urn",       slots: ['yellow', 'yellow', 'red'] },
  ],
  scholar: [
    { id: 'scholar_urn',      name: "Scholar's Urn",              slots: ['blue', 'green', 'green'], isDLC: true },
    { id: 'scholar_goblet',   name: "Scholar's Goblet",           slots: ['red', 'blue', 'yellow'], isDLC: true },
    { id: 'scholar_chalice',  name: "Scholar's Chalice",          slots: ['yellow', 'green', 'white'], isDLC: true },
    { id: 'scholar_soot',     name: "Soot-Covered Scholar's Urn", slots: ['red', 'red', 'green'], isDLC: true },
    { id: 'scholar_sealed',   name: "Sealed Scholar's Urn",       slots: ['green', 'green', 'red'], isDLC: true },
  ],
  undertaker: [
    { id: 'undertaker_urn',      name: "Undertaker's Urn",              slots: ['red', 'yellow', 'yellow'], isDLC: true },
    { id: 'undertaker_goblet',   name: "Undertaker's Goblet",           slots: ['red', 'blue', 'green'], isDLC: true },
    { id: 'undertaker_chalice',  name: "Undertaker's Chalice",          slots: ['red', 'red', 'white'], isDLC: true },
    { id: 'undertaker_soot',     name: "Soot-Covered Undertaker's Urn", slots: ['red', 'red', 'blue'], isDLC: true },
    { id: 'undertaker_sealed',   name: "Sealed Undertaker's Urn",       slots: ['yellow', 'yellow', 'red'], isDLC: true },
  ],
};
